---
- import_role:
    name: nomad_service

- name: update apt cache
  apt:
    update_cache: yes

- name: install docker and openjdk
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker.io

- name: start docker service
  service:
    name: docker
    state: started
- name: create directory
  file:
     path: /etc/systemd/resolved.conf.d/
     state: directory
     mode: 0755
     group: root
     owner: root
- name: copy nomad config
  template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
- name: copy dns config
  template: 
    src: consul.conf.j2
    dest: /etc/systemd/resolved.conf.d/consul.conf
- name: Restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: systemd-resolved
- name: start nomad
  service:
    name: nomad
    state: restarted
    enabled: yes
